server:
  port: 8088

spring:
  data:
    mongodb:
     uri: mongodb://localhost:27017/crud-service
     #uri: mongodb://localhost:27017/merchant
    
  jackson:
    default-property-inclusion: NON_NULL
    serialization:
      write-dates-as-timestamps: false
